### ISSUE TITLE
SVG example fails because expected fonts are missing from OS

### ISSUE THREAD

**Issue by villares** [xxao/pero#2]
I'm on Manjaro Linux and I think I don't have Arial or Helvetica.

Running this example:

```python
import pero

# init size
width = 200
height = 200

# init canvas
canvas = pero.svg.SVGCanvas(width=width, height=height)

# draw graphics
canvas.line_color = "b"
canvas.fill_color = "w"
canvas.fill()
canvas.draw_circle(100, 100, 75)

# save to file
with open('test.svg', 'w', encoding='utf-8') as f:
    f.write(canvas.get_xml())
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/villares/GitHub/sketch-a-day/2022/sketch_2022_12_12/sketch_2022_12_12.py", line 9, in <module>
    canvas = pero.svg.SVGCanvas(width=width, height=height)
  File "/home/villares/.local/lib/python3.10/site-packages/pero/backends/svg/canvas.py", line 56, in __init__
    self._update_text()
  File "/home/villares/.local/lib/python3.10/site-packages/pero/backends/svg/canvas.py", line 723, in _update_text
    font = self.get_font()
  File "/home/villares/.local/lib/python3.10/site-packages/pero/drawing/canvas.py", line 366, in get_font
    raise ValueError(message)
ValueError: Cannot initialize the font! -> Arial, arial, Arial, Helvetica
```

**Comment by xxao** [comment]
The overal font handling is now significantly improved and some more substitutions are now available.

**Comment by xxao** [comment]
Oh, it looks like I completely missed fonts loading on linux. Hopefully it is now fixed in v0.23.0.

**Comment by xxao** [comment]
That's not good. Could you please run this to see if any font is loaded:

import pero
for font in pero.FONTS.fonts:
    print(font.name)

**Comment by villares** [comment]
I'm afraid no font is being found 😢 

```python
>>> import pero
>>> for font in pero.FONTS.fonts: print(font.name)

>>> len(pero.FONTS.fonts)
0
>>> pero.FONTS.fonts
()
>>> import py5
>>> len(py5.Py5Font.list())
1007
>>> py5.Py5Font.list()[:5]
['Adwaita Mono', 'Adwaita Mono Bold', 'Adwaita Mono Bold Italic', 'Adwaita Mono Italic', 'Adwaita Sans']
>>> 'Liberation Sans' in py5.Py5Font.list()
True
```

<img width="951" height="692" alt="Image" src="https://github.com/user-attachments/assets/d1ff2ea1-cd38-4b08-acf2-da4fa37529e8" />

<img width="940" height="837" alt="Image" src="https://github.com/user-attachments/assets/fc24386b-73db-4f36-a650-5b9bcd4127e5" />

**Comment by xxao** [comment]
Ok I see the problem - all the fonts are within their own folders. Should be fixed now in 0.24.0

**Comment by villares** [comment]
Success!  🥳 

```python
>>> for font in pero.FONTS.fonts[:5]: print(font.name)
Adwaita Mono
Adwaita Mono
Adwaita Mono
Adwaita Mono
Adwaita Mono
>>> len(pero.FONTS.fonts)
1798
```
